### ISSUE TITLE
Skin change still doesn't work on newest version

### ISSUE THREAD

**Issue by SilverSpireZ** [cobrasrock/Skin-Swapper#12] opened 2021-03-26 00:19 UTC
I'm using version 2.0.2 of the Skin Swapper mod, but I'm still having issues changing skins. I click Yes when confirming to switch, but it still uses the previous skin. Tried with all other mods disabled except for Fabric API, but still having problems. No idea what the problem is...

**Comment by JonathanTippy** [comment] 2021-08-20 23:51
i have the same problem. it used to work, but it's stopped working.

**Comment by cobrasrock** [comment] 2021-08-20 23:56
Very odd. Out of curiosity have you migrated your account to microsoft? Perhaps there is a different protocol.

**Comment by JonathanTippy** [comment] 2021-08-20 23:57
no, i haven't migrated my account. i'm using version 2.1.2 on 1.17.1 and it worked a few weeks ago, but it doesn't now.

**Comment by JonathanTippy** [comment] 2021-08-20 23:57
lol whoops i mean version 2.1.0

**Comment by cobrasrock** [comment] 2021-08-21 00:01
> no, i haven't migrated my account. i'm using version 2.1.2 on 1.17.1 and it worked a few weeks ago, but it doesn't now.

Can you verify with namemc that it isn't changing? I want to see if this is a clientside or serverside bug.

**Comment by JonathanTippy** [comment] 2021-08-21 00:04
yup, i just checked and when i change my skin with skinswapper it does not update on namemc. it only updates if i close the game and use the  launcher's built-in skin changer.

**Comment by cobrasrock** [comment] 2021-08-21 11:46
> yup, i just checked and when i change my skin with skinswapper it does not update on namemc. it only updates if i close the game and use the launcher's built-in skin changer.

I am sorry but for now I don't really know what I can do regarding the issue. Very soon I hope to release a new version that has better logs/cleaner code so I could pinpoint the issue better.

**Comment by Copernicle** [comment] 2021-08-26 19:55
I have a similar issue, however this issue (skin doesn't change) only affected me when I migrated my account, before that it worked. I am supposing that the migration has changed protocol and has caused the mod to break. Are you planning on supporting migrated accounts? (Great helpful and quick mod BTW)

**Comment by cobrasrock** [comment] 2021-08-27 10:48
> I have a similar issue, however this issue (skin doesn't change) only affected me when I migrated my account, before that it worked. I am supposing that the migration has changed protocol and has caused the mod to break. Are you planning on supporting migrated accounts? (Great helpful and quick mod BTW)

I have been working on a newer version with cleaner code and better diagnostics. When I originally wrote the mod, I was pretty inexperienced with java and writing mods. I suspect the issue is either caused by my sloppy coding or is related to account migration which may have changed the protocol. I probably should add a warning to the curseforge page until I get the issue resolved. Worst case scenario, I will decompile the launcher and see how it changes your skin there.

**Comment by cobrasrock** [comment] 2021-08-27 12:42
I believe I have fixed the issue. It appears that mojang changed the protocol a bit.

**Comment by cobrasrock** [comment] 2021-08-27 15:02
This issue should be fixed in the latest version 2.3.0. Hopefully mojang doesn't change things again.

**Closed as completed by cobrasrock** 2021-08-27 15:02 UTC

**Comment by Copernicle** [comment] 2021-08-27 23:58
It works now! Great Job, and nice upgrades in the GUI!

**Comment by JonathanTippy** [comment] 2021-08-28 00:02
it also works for me on the newer version! great gui changes, but it would be cool to be able to see the back of the skins. (maybe you could drag to rotate it?)
