### ISSUE TITLE
Crash of the game when trying to change the skin and log on to the server

### ISSUE THREAD

**Issue by Disguys** [cobrasrock/Skin-Swapper#24] opened 2021-12-24 17:45 UTC
Hello, I into problem on version 1.17, the problem also sometimes occurs in 1.18. The thing is that for some reason, after I change the skin and go to the server after that, sometimes minecraft refuses to receive textures of skins, after which the game crashes, only restarting the game helps, but after that the game also crashes until you delete the mod from the folder.

Crash reports:
ByteBin- https://bytebin.lucko.me/btkgW2MNIM
Crashy - https://crashy.net/UUeVvFhhW5tGbF5a0Rqr

**Comment by cobrasrock** [comment] 2021-12-24 19:22
Thank you for the report. Unfortunately I can't get to fixing it for a few days. I believe the issue has something to do with how I clear the skin cache. Also seen in #23

**Comment by Disguys** [comment] 2021-12-24 20:59
Ok, I'll wait fix, thanks for answer.

**Comment by srnyx** [comment] 2021-12-26 15:32
Duplicate of #23, @Disguys please close this

**Closed as completed** 2021-12-27 23:36 UTC
